### ISSUE TITLE
The plugin `nbrg_pdf_viewer_flutter` uses a deprecated version of the Android embedding.

### ISSUE THREAD

**Issue by tanwanlanyue1** [nbrgdevelopers41/nbrg_pdf_viewer_flutter#1]
The plugin `nbrg_pdf_viewer_flutter` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing
it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

**Comment by namangor04** [comment]
Will try to migrate the plugin soon sir!

**Comment by namangor04** [comment]
I have started to migrate this plugin, Will update it ASAP.

**Comment by namangor04** [comment]
The plugin has been migrated to Android Embedding V2, hence closing the issue. Thank you for filing this issue. If you face anymore issues, we are here to help! :)
